### PR TITLE
Added component-separated noise curves and basic README

### PR DESCRIPTION
**Pull request by jcolinhill**

### CODE REVIEW

**Comment by mhasself** [comment]
Thanks... a few requests:

1. Wrap readme lines at 78 chars or so.  Perhaps add a release date to the README?  Helps for context.

2. a) Is it possible to commit the code that generates these files, instead of the resulting spectra?  Fine if not.

2. b) If not, I would like to compress these curves a bit more... instead of 
```
   4.000000000000000000e+01 1.023331722181667133e-04 3.711655916056646365e-17
```
can we do:
```
   40. 1.02e-04 3.71e-17
```
That will save a factor of 4 or so, with no loss of information.  The sampling at every single ell is overkill too, but I know it's convenient for consumers...

3.  Can we put these files in subdirectory LAT_comp_sep_noise/v3.1.0/?  That will leave us room to grow.

**Comment by jcolinhill** [comment]
Thanks Matthew -- I'll take care of this later today.  The files from the original release (on the SO public site) were formatted/organized much more nicely and compactly, but I had more free time a year ago :-|

The code for these is unfortunately not in a widely usable state, but moreover I am wary of providing such a tool, because it would be likely to be mis-used.  I think these noise curves cover a very wide variety of use cases, and are much more user-friendly than having people learn how to run the calculations ab initio.

**Comment by jcolinhill** [comment]
OK, I've made all of the requested changes.  It turned out I had already written a script to re-format everything nicely, so I just ran that... I didn't remove as many significant figures as desired, but if you *really* feel that saving the further space is necessary, I can re-run with more digits removed.

I also agree that the sampling at every ell is overkill, but in practice it makes users' lives a little easier...

**Comment by jcolinhill** [comment]
ping @mhasself

**Pull request merged**
